// Claude-ийн бичсэн энгийн текст (одоогийн Make.com prompt-уудын хэрэглэдэг
// "N. ТОМ ҮСГЭЭР ГАРЧИГ" конвенцтой) хэлбэрийг docxBuilder.js-ийн хүлээж авдаг
// typed "sections" блокийн массив (h1/h2/bullet/p) болгон хөрвүүлнэ.
//
// Зорилго: Make.com дээр Claude-ээс шууд JSON блок буцаалгахыг шаардахгүйгээр
// (энэ нь найдваргүй, алдаа гарах эрсдэлтэй) — өнөөдөр production дээр аль
// хэдийн ажиллаж байгаа энгийн текст гаралтыг ашиглан найдвартай парс хийх.

const TOP_HEADING_RE = /^\s*(\d{1,2})\.\s+([^\n]{2,120})\s*$/u;
const SUB_HEADING_RE = /^\s*(\d{1,2})\.(\d{1,2})\.?\s+(.+)$/u;
const BULLET_RE = /^\s*[-•‣●*]\s+(.+)$/u;

function isMostlyUpperCase(line) {
  const letters = line.replace(/[^A-Za-zА-Яа-яЁёӨөҮү]/g, "");
    if (letters.length < 3) return false;
      const upper = letters.toUpperCase();
        const lower = letters.toLowerCase();
          return letters === upper && upper !== lower;
          }

          /**
           * @param {string} fullText
            * @returns {Array<{type:string, text:string}>}
             */
             function parseTextToSections(fullText) {
               const lines = String(fullText || "").replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
                 const blocks = [];
                   let paraBuffer = [];

                     function flushPara() {
                         if (paraBuffer.length) {
                               const text = paraBuffer.join(" ").replace(/\s+/g, " ").trim();
                                     if (text) blocks.push({ type: "p", text });
                                           paraBuffer = [];
                                               }
                                                 }

                                                   for (const rawLine of lines) {
                                                       const line = rawLine.trim();
                                                           if (!line) {
                                                                 flushPara();
                                                                       continue;
                                                                           }

                                                                               let m = TOP_HEADING_RE.exec(line);
                                                                                   if (m && isMostlyUpperCase(m[2])) {
                                                                                         flushPara();
                                                                                               blocks.push({ type: "h1", text: `${m[1]}. ${m[2].trim()}` });
                                                                                                     continue;
                                                                                                         }
                                                                                                         
                                                                                                             m = SUB_HEADING_RE.exec(line);
                                                                                                                 if (m) {
                                                                                                                       flushPara();
                                                                                                                             blocks.push({ type: "h2", text: line });
                                                                                                                                   continue;
                                                                                                                                       }
                                                                                                                                       
                                                                                                                                       // Гарчигтай төстөй, богино, бүхэлдээ том үсэгтэй мөр (дугааргүй ч гэсэн) -> h2 fallback
                                                                                                                                           if (line.length <= 90 && isMostlyUpperCase(line) && !/[.!?]\s+\S/.test(line)) {
                                                                                                                                                 flushPara();
                                                                                                                                                       blocks.push({ type: "h2", text: line });
                                                                                                                                                             continue;
                                                                                                                                                                 }
                                                                                                                                                                 
                                                                                                                                                                     m = BULLET_RE.exec(line);
                                                                                                                                                                         if (m) {
                                                                                                                                                                               flushPara();
                                                                                                                                                                                     blocks.push({ type: "bullet", text: m[1].trim() });
                                                                                                                                                                                           continue;
                                                                                                                                                                                               }
                                                                                                                                                                                               
                                                                                                                                                                                                   paraBuffer.push(line);
                                                                                                                                                                                                     }
                                                                                                                                                                                                       flushPara();
                                                                                                                                                                                                         return blocks;
                                                                                                                                                                                                         }
                                                                                                                                                                                                         
                                                                                                                                                                                                         function fmt(n) {
                                                                                                                                                                                                           if (n === null || n === undefined || Number.isNaN(n)) return "-";
                                                                                                                                                                                                             return Number(n).toLocaleString("mn-MN");
                                                                                                                                                                                                             }
                                                                                                                                                                                                             
                                                                                                                                                                                                             /**
                                                                                                                                                                                                              * /calc/finance ба /calc/payroll-ийн үр дүнгээс "sections" блокуудыг угсарна
                                                                                                                                                                                                               * (хүснэгт + график) — эдгээрийг Claude биш, шууд бодит тоогоор угсардаг тул
                                                                                                                                                                                                                * тоо "зохиогдох" эрсдэлгүй.
                                                                                                                                                                                                                 */
                                                                                                                                                                                                                 function buildFinanceSections(finance, payroll) {
                                                                                                                                                                                                                   const blocks = [];
                                                                                                                                                                                                                     if (finance && !finance.error) {
                                                                                                                                                                                                                         blocks.push({ type: "h2", text: "Тооцоолсон санхүүгийн үндсэн үзүүлэлтүүд" });
                                                                                                                                                                                                                             const rows = [
                                                                                                                                                                                                                                   ["Нийт хөрөнгө оруулалт", `${fmt(finance.total_investment)}₮`],
                                                                                                                                                                                                                                         ["Цэвэр өнөөгийн үнэ цэн (НПВ)", `${fmt(finance.npv)}₮`],
                                                                                                                                                                                                                                               ["Дотоод тохирлын хувь (ДТОХ/IRR)", finance.irr != null ? `${finance.irr}%` : "Тооцоологдохгүй"],
                                                                                                                                                                                                                                                     ["Эргэн төлөгдөх хугацаа", finance.payback_period_years != null ? `${finance.payback_period_years} жил` : "Тооцоологдохгүй (хугацаанд багтахгүй)"],
                                                                                                                                                                                                                                                         ];
                                                                                                                                                                                                                                                             if (finance.roi != null) rows.push([`ROI (${finance.roi_year_used}-р жилээр)`, `${finance.roi}%`]);
                                                                                                                                                                                                                                                                 if (finance.break_even_point && !finance.break_even_point.error) {
                                                                                                                                                                                                                                                                       rows.push(["Ашгийн хугарлын цэг (нэгжээр)", `${fmt(finance.break_even_point.units)}`]);
                                                                                                                                                                                                                                                                             rows.push(["Ашгийн хугарлын цэг (орлогоор)", `${fmt(finance.break_even_point.revenue)}₮`]);
                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                     blocks.push({ type: "table", headers: ["Үзүүлэлт", "Утга"], rows });
                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                     if (Array.isArray(finance.cumulative_cash_flow_by_year) && finance.cumulative_cash_flow_by_year.length) {
                                                                                                                                                                                                                                                                                           blocks.push({
                                                                                                                                                                                                                                                                                                   type: "chart",
                                                                                                                                                                                                                                                                                                           chart_type: "bar",
                                                                                                                                                                                                                                                                                                                   title: "Мөнгөн урсгалын төлөвлөгөө (жилээр)",
                                                                                                                                                                                                                                                                                                                           labels: finance.cumulative_cash_flow_by_year.map((r) => `Жил ${r.year}`),
                                                                                                                                                                                                                                                                                                                                   series: [
                                                                                                                                                                                                                                                                                                                                             { name: "Жилийн цэвэр мөнгөн урсгал", values: finance.cumulative_cash_flow_by_year.map((r) => r.cash_flow) },
                                                                                                                                                                                                                                                                                                                                                       { name: "Хуримтлагдсан мөнгөн урсгал", values: finance.cumulative_cash_flow_by_year.map((r) => r.cumulative) },
                                                                                                                                                                                                                                                                                                                                                               ],
                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                             if (finance.npv_discount_rate_used != null) {
                                                                                                                                                                                                                                                                                                                                                                                   blocks.push({ type: "note", text: `НПВ тооцоолол ${Math.round(finance.npv_discount_rate_used * 100)}% хөнгөрүүлэх хувиар тооцоологдсон.` });
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                         if (payroll && Array.isArray(payroll.positions) && payroll.positions.length) {
                                                                                                                                                                                                                                                                                                                                                                                             blocks.push({ type: "h2", text: "Хүнийн нөөцийн зардлын задаргаа (сар бүр)" });
                                                                                                                                                                                                                                                                                                                                                                                                 const headers = ["Албан тушаал", "Тоо", "Үндсэн цалин", "НД (ажилчин)", "ХХОАТ", "Гарт олгох", "НД (ажил олгогч)", "Нийт зардал"];
                                                                                                                                                                                                                                                                                                                                                                                                     const rows = payroll.positions.map((p) => [
                                                                                                                                                                                                                                                                                                                                                                                                           p.title,
                                                                                                                                                                                                                                                                                                                                                                                                                 String(p.count),
                                                                                                                                                                                                                                                                                                                                                                                                                       `${fmt(p.gross_salary)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                             `${fmt(p.employee_social_insurance)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                                   `${fmt(p.income_tax)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                                         `${fmt(p.net_pay)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                                               `${fmt(p.employer_social_insurance)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                     `${fmt(p.total_employer_cost_all)}₮`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                         ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             rows.push(["НИЙТ", "", "", "", "", "", "", `${fmt(payroll.total_monthly_employer_cost)}₮`]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 blocks.push({ type: "table", headers, rows });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (payroll.total_annual_employer_cost) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           blocks.push({ type: "note", text: `Жилийн нийт хүнийн нөөцийн зардал: ${fmt(payroll.total_annual_employer_cost)}₮.` });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (payroll.warning) blocks.push({ type: "note", text: payroll.warning });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (payroll.positions.length > 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             blocks.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type: "chart",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             chart_type: "pie",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     title: "Албан тушаал тус бүрийн нийт зардлын эзлэх хувь",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             labels: payroll.positions.map((p) => p.title),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     values: payroll.positions.map((p) => p.total_employer_cost_all),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return blocks;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * parseTextToSections-ийн үр дүн рүү санхүү/цалингийн блокуудыг зохих
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * бүлгийн дараа (гарчиг match хийсэн h1-ийн дараа) шигтгэнэ; олдохгүй бол
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * төгсгөлд нь нэмэлт бүлэг болгон хавсаргана.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   function mergeFinanceIntoSections(parsedBlocks, financeSections, headingMatch) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!financeSections.length) return parsedBlocks;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const matchStr = (headingMatch || "САНХҮҮ").toUpperCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const idx = parsedBlocks.findIndex((b) => b.type === "h1" && b.text.toUpperCase().includes(matchStr));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (idx >= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return [...parsedBlocks.slice(0, idx + 1), ...financeSections, ...parsedBlocks.slice(idx + 1)];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return [...parsedBlocks, { type: "h1", text: "НЭМЭЛТ. САНХҮҮГИЙН ТООЦООЛОЛ" }, ...financeSections];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   module.exports = { parseTextToSections, buildFinanceSections, mergeFinanceIntoSections };
